### ISSUE TITLE
Conflict with lando app name and internal node app name

### ISSUE THREAD

**Issue by pi-ron** [kalabox/lando#104]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/lando/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/lando/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

`v3.0.0-alpha.4-12-gb79d`

Mac OSX `10.12.3`

Have you previously installed lando? If so, what version?

*Yes, I've installed lando v3.0.0-alpha4*

**Tell us about your bug**

I'm running a Drupal 8 app, the Drupal subtheme uses npm etc. for frontend styling.

Drupal theme is called `stt`, same as lando app name `stt`

After lando start, `cd` to theme directory on host machine.

`pwd` and
`lando ssh -c "echo $(pwd)"`
Outputs same path

Running `lando gulp` spits out errors ie. `[23:30:01] Local gulp not found in /app/code/themes` along with, package.json not found at `/app/code/themes`

Note that path, it should be `app/code/themes/stt`

Clone the lando app and changed it's name to `stt-landawg`, npm stuff now works within my theme directory.

Lando.yml:

``````
# Drupal 8 recipe
name: stt
# Start with the default Drupal 8 recipe
recipe: drupal8
# Configure the Drupal8 recipe
config:
  php: '7.1'
  via: nginx
  webroot: code
  drush: stable
  drupal: true

# Services
services:
  database:
    type: mysql
    portforward: 3307
  node:
    type: node:6.10
    globals:
      gulp-cli: "latest"
      node-sass: "latest"
    build:
          - "cd $LANDO_MOUNT/themes/stt && npm run setup"
  cache:
    type: redis
    persist: true

tooling:
  redis-cli:
    service: cache
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node

``````

**Tell us more**

Does this bug prevent you from using lando?

Nope
