### ISSUE TITLE
Write a tutorial on how to run behat with lando (and in CI with lando)

### ISSUE THREAD

**Issue by pirog** [kalabox/lando#149]

**Comment by serundeputy** [comment]
I started on this today.  Here is what I've got:

* started with Pantheon `example-drops-8-composer` as it has a composer with Behat and friends in it.

```bash
composer create-project pantheon-systems/example-drops-8-composer behat-d8
lando init behat-d8
lando drush si --db-url=mysql://drupal8:drupal8@database/drupal8
```

In `tests/behat-pantheon.yml` I had to add to the `drush` section beneath the `api_driver` section like so:

```yaml
#
# behat.yml file for testing on Pantheon.
#
default:
  suites:
    default:
      paths:
        - %paths.base%/features
        - %paths.base%/site-features
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      files_path: './data-files'
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drush'
      drush:
        alias: 'local'
```

Behat tries to write to `/tmp` files, but in the container they are owned by `root` so I changed the ownership there to `www-data`:

```bash
lando ssh
chmod -R www-data:www-data /tmp
```

We'll want a way to have that set up already for the user `extras` key in `.lando.yml`?
