### ISSUE TITLE
MariaDB is defaulting to latin1 charset, not UTF-8

### ISSUE THREAD

**Issue by Proof757** [kalabox/lando#182]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/lando/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/lando/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

v3.0.0-alpha.17 on OS X El Capitan v10.11.6 

Have you previously installed lando? If so, what version?

Yes, i've installed v3.0.0-alpha.16

**Tell us about your bug**

1. Pulled site down D8 site from Pantheon
2. Configured .lando.yml
```
name: decoupled-sandbox
recipe: pantheon
config:
  framework: drupal8
  env: dev
  (removing UUID and site-id)
services:
  node:
    type: node:latest
tooling:
  node:
    service: node
  npm:
    service: node
```
3. Ran `lando start`
4. Ran `lando mysql`
5. Ran `status` in mysql
6. 
![image](https://user-images.githubusercontent.com/945181/28393310-134d419a-6cb4-11e7-9f40-a34cbc965f62.png)

**Tell us more**
Not sure how to tag this exactly but i'm using Lando (its great btw) on a Drupal 8 project hosted on Pantheon. I noticed MariaDB's character-set's are `latin1`, not `utf-8` like on Pantheon. I looked into why that is and it seems if the charset isn't set in my.cnf, the default is latin1. I checked here: https://github.com/kalabox/lando/blob/master/plugins/lando-recipes/pantheon/mysql/my.cnf and it looks like there's no charset set. It's an easy enough issue to circumvent, but this is the fix in my environment's my.cnf

```
character-set-server = utf8
collation-server = utf8_general_ci
character_set_server = utf8
collation_server = utf8_general_ci
```

Thanks!
