### ISSUE TITLE
Build steps in .lando.yml seem to break drush.

### ISSUE THREAD

**Issue by serundeputy** [kalabox/lando#228]
Bug Report
==========

**Tell us about your setup**

* Mac OS
* Lando: v3.0.0-alpha.18

**Tell us about your bug**

When I add a `build` step to my `.lando.yml` file it prevents drush from working.  Here is my `.lando.yml`:

```yaml
name: composer-drupal7
recipe: drupal7
config:
  webroot: web
# services:
#   appserver:
#     # Add a Build Step to your App.
#     build:
#       - "cd $LANDO_MOUNT && composer install"
```

With the build section commented out if I start the app I can use drush normally, but once I add it in and restart the app I can no longer use drush.

Here is the error I receive when trying to use drush:

```
geoff@yep web $ lando.dev drush st
/bin/sh: 1: drush: not found
error: /bin/sh: 1: drush: not found
```

but if you comment out the build step from the `.lando.yml` file, build the app and then add teh `build` step back in and restart the app you can still use drush.  So something is amiss.
