### ISSUE TITLE
Tooling commands should support non-arrayed delegation

### ISSUE THREAD

**Issue by pirog** [kalabox/lando#282]
## Good

```yaml
tooling:
  test:
    service: appserver
    cmd: 
      - composer
      - test
```
## Bad

```yaml
tooling:
  test:
    service: appserver
    cmd: composer test
```

We should probably support both, arrayifying a long command is probably going to be super annoying
