### ISSUE TITLE
All initial pulls on Pantheon git repos fails

### ISSUE THREAD

**Issue by labboy0276** [kalabox/lando#296]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

Lando Beta 10 + Ubuntu 16.04

**Tell us about your `.lando.yml`**

```yml
name: progenitycom
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: progenitycom
  id: I removed this
  webroot: www
  xdebug: true
  php: '5.6'
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
john@kalamuna:~/lando/progms$ lando init progms
? What recipe do you want to use? pantheon
? Choose a Pantheon account john@kalamuna.com
? Which site? progenitycom
john@kalamuna:~/lando/progms$ lando start
john@kalamuna:~/lando/progms$ lando pull
? Pull code from? dev
? Pull DB from? dev
? Pull files from? dev
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Verifying that you are logged in and authenticated by getting info about progenitycom...

```

**Tell us about the error you got**

See the Git error above, happens on every pantheon Instance I pull.  I can manually pull the gits and it is fine after that.

*Example:*

```bash
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
