### ISSUE TITLE
Add django recipe

### ISSUE THREAD

**Issue by pirog** [kalabox/lando#318]

**Comment by pmackay** [comment]
Are there any existing examples where Django has been used with Lando that you know of?

**Comment by pirog** [comment]
Beyond running an extremely trivial example on my own... no... not currently. Lando was born out of the php space so its currently much less mature and stable in the other languages it supports. 

Comments like this are great though since they help us focus priorities.

**Comment by UltraBob** [comment]
Just to add an upvote for having django and/or flask recipes.  I use lando for my php dev, and it would be nice to be able to add python into the mix on these.  I was going to try to see what I could come up with on my own, but can't even get the example python setup to start.

**Comment by yhoiseth** [comment]
@pirog It's not entirely clear to me why this issue was closed. I'm asking because a Django recipe would be really useful to me :)

**Comment by serundeputy** [comment]
I needed a thing.

## `.lando.yml`
```yaml
name: gspc
services:
  appserver:
    type: python:3.10
    command: python manage.py runserver 0:8800
    build:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  database:
    type: mariadb
proxy:
  appserver:
    - gspc.lndo.site:8800
tooling:
  python:
    service: appserver
    cmd: python
  pip:
    service: appserver
    cmd: pip
```

## `requirements.txt`
```
asgiref==3.5.2
Django==4.0.4
sqlparse==0.4.2
```

## `settings.py`
Set the allowed urls
```python
.
.
.
ALLOWED_HOSTS = [
    'gspc.lndo.site'
]
.
.
.
```
